### ISSUE TITLE
Generar Resumen de Base de Datos

### ISSUE THREAD

**Issue by ovejerojose** [ovejerojose/Programador2022#2]
Podemos agregar glosario, enlaces a sitios o canales recomendados.

**Comment by JosePolvora** [comment]
Video explicativo de que son, Bases de Datos 👇👇👇

https://youtu.be/SKOiEXlFNeM

**Comment by MatiiVargas** [comment]
**Modelo Entidad-Relación**
Cuando empezamos a pensar o diseñar una base de datos, puede parecer simple en un principio, pero en la medida que nuestra idea de base de datos crece, el diseño también crece y necesitamos una forma de poder conceptualizar y visualizar todos los elementos que la componen, cómo se relacionan y qué características tienen.

Entonces denominado por sus siglas como: E-R, este modelo representación de la realidad a través de entidades, que son objetos que existen y que se distinguen de otros por sus características, por ejemplo: un alumno se distingue de otro por sus características particulares como lo es el nombre, o el número de control asignado al entrar a una institución educativa, así mismo, un empleado, una materia, etc. 

La siguiente imagen ilustra un DER:
![image](https://user-images.githubusercontent.com/94567789/172232897-0f238c5b-aa41-48d7-8cae-5052bad5412c.png)

Hay tres elementos básicos en un modelo ER: 

1. **Entidad**
2. **Atributo**
3. **Relación**

**Entidad:** Una entidad representa una “cosa”, "objeto" o "concepto" del mundo real.

_Algunos ejemplos:_

Una persona: se diferencia de cualquier otra persona, incluso siendo gemelos.

Un automóvil: aunque sean de la misma marca, el mismo modelo, etc, tendrán atributos diferentes, por ejemplo, el número de chasis.

Una casa: aunque sea exactamente igual a otra, aún se diferenciará en su dirección

**Atributos:** Los atributos son las características que definen o identifican a una entidad. como por ejemplo, para una entidad Persona tenemos: Edad, género, peso, altura, etc.

Veamos otro ejemplo: Consideremos una empresa que requiere controlar a los vendedores y las ventas que ellos realizan; de este problema determinamos que los objetos o entidades principales a estudiar son el empleado (vendedor) y el artículo (que es el producto en venta), y las características que los identifican son: 

Empleado: Nombre, Puesto, Salario, Numero de Empleado

Artículo: Nombre Descripción Costo

**Conjunto de relaciones**: Consiste en una colección, o conjunto, de relaciones entre las entidades. Por ejemplo: Dadas las entidades  "Habitación" y "Huésped", la relación que podemos tener es que uno o más huéspedes estarán alojados en una habitación. Además a esta relación le podemos dar un título: “Se aloja” ya que los huéspedes se alojan en las habitaciones.

Las relaciones entre las entidades se pueden agrupar en 3 tipos según su finalidad.

Cardinalidad de las relaciones 

La cardinalidad de un atributo indica el número mínimo y el número máximo de valores que puede tomar para cada ocurrencia de la entidad o relación a la que pertenece. El tipo de cardinalidad se representa mediante una etiqueta en el exterior de la relación, respectivamente: "1:1", "1:N" y "N:M".

- Uno a Uno (1:1) se da cuando un elemento de una entidad se puede relacionar solamente con un solo registro de otra entidad y viceversa. 

- Uno a Muchos (1:M) se da cuando un registro de una entidad A se puede relacionar con cero o muchos registros de otra entidad B y cada registro de la entidad B se relaciona con un sólo registro de la entidad A. 

- Muchos a Muchos (N:M) se da cuando un registro de una entidad se relaciona con cero o varios registros de otra entidad


Si tuviéramos el caso de una base de datos de una escuela podríamos pensar en las siguientes relaciones:

Un alumno de una escuela puede estar solamente en un solo curso (1:1)

En una materia de la escuela, un alumno tendrá varias notas durante el año (1:N)

En la universidad, un alumno puede estar en muchas clases, y las clases pueden tener alumnos de diferentes carreras (N:N)
